version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - /home/outscale/db_init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/postgres'
